name: 'Setup Metaplay CLI'
description: 'Set up the Metaplay CLI and sign in with the provided machine user credentials'
inputs:
  version:
    description: 'Metaplay CLI version to install'
    required: false
    default: 'latest'
  credentials:
    description: 'Metaplay machine user credentials'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install Metaplay CLI
      shell: bash
      run: |
        if [ "${{ inputs.version }}" = "latest" ]; then
          bash <(curl -fsSL https://metaplay.github.io/cli/install.sh)
        else
          bash <(curl -fsSL https://metaplay.github.io/cli/install.sh) --version ${{ inputs.version }}
        fi

    - name: Authenticate to Metaplay cloud
      shell: bash
      run: |
        export METAPLAY_CREDENTIALS=${{ inputs.credentials }}
        metaplay auth machine-login
